apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: cloudflare-dns
type: Opaque
stringData:
  # ⚠️ remplacé automatiquement par ton token Cloudflare (Bitwarden)
  api-token: "${CLOUDFLARE_API_TOKEN}"
