apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:9.3.0  # Utilisation de l'image MySQL 9.3.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
              name: mysql
          envFrom:
            - secretRef:
                name: mysql-credentials  # Utilisation des credentials pour la DB
          args:
            - "--skip-name-resolve"
            - "--max_connections=200"
            - "--explicit_defaults_for_timestamp"
          securityContext:
            runAsNonRoot: true
            runAsUser: 999           # utilisateur mysql dans l'image officielle
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          readinessProbe:
            exec:
              command:
                - "mysqladmin"
                - "ping"
                - "-h"
                - "127.0.0.1"
                - "-pxwiki"
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql  # Le répertoire des données
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
