apiVersion: apps/v1
kind: Deployment
metadata:
  name: xwiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xwiki
  template:
    metadata:
      labels:
        app: xwiki
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1000   # groupe qui possèdera les fichiers du volume

      containers:
        - name: xwiki
          image: xwiki:17.3.0-mysql-tomcat
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: MYSQL_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: MYSQL_DATABASE
            - name: DB_HOST
              value: mysql
          # Durcissement du container
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: xwiki-data
              mountPath: /usr/local/xwiki/data
      volumes:
        - name: xwiki-data
          persistentVolumeClaim:
            claimName: xwiki-data
