# manifests/xwiki/base/kustomization.yaml

resources:
  - 01-secrets.yaml
  - 02-mysql.yaml
  - 02-mysql-service.yaml
  - 03-xwiki.yaml
  - 03-xwiki-pvc.yaml
  - 04-service-xwiki.yaml
  - 05-ingress.yaml
