apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xwiki-cert
  namespace: integration
spec:
  secretName: xwiki-cert-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: 'xwiki.integration.nudger.logo-solutions.fr'
  dnsNames:
    - 'xwiki.integration.nudger.logo-solutions.fr'
    - 'www.xwiki.integration.nudger.logo-solutions.fr'
  duration: 2160h
  renewBefore: 360h
