# overlays/integration/01-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: integration  # Mise à jour ici
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root-password-integration"
  MYSQL_USER: "xwiki"
  MYSQL_PASSWORD: "xwiki-integration"
  MYSQL_DATABASE: "xwiki"
