apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysqlint
  namespace: integration
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysqlint
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: mysql:9.3.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
              name: mysql
          envFrom:
            - secretRef:
                name: mysql-credentials
          args:
            - "--skip-name-resolve"
            - "--max_connections=200"
            - "--explicit_defaults_for_timestamp"
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "127.0.0.1", "-pxwiki"]
            initialDelaySeconds: 15
            periodSeconds: 10
          lifecycle:
            postStart:
              exec:
                command:
                  - bash
                  - -c
                  - |
                    echo "⚙️ Importation du dump MySQL..."
                    mysql -u root -pxwiki < /mnt/dump/xwiki.sql
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: sql-dump
              mountPath: /mnt/dump  # Monte le fichier SQL ici
      volumes:
        - name: sql-dump
          configMap:
            name: xwiki-dump   # Le ConfigMap contenant ton fichier SQL
  volumeClaimTemplates:
    - metadata:
        name: dataint
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 2Gi
