apiVersion: apps/v1
kind: Deployment
metadata:
  name: xwiki
  namespace: xwiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xwiki
  template:
    metadata:
      labels:
        app: xwiki
    spec:
      containers:
        - name: xwiki
          image: xwiki:17.3.0-mysql-tomcat
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: MYSQL_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: MYSQL_DATABASE
            - name: DB_HOST
              value: mysql
          volumeMounts:
            - name: xwiki-data
              mountPath: /usr/local/xwiki/data
      volumes:
        - name: xwiki-data
          persistentVolumeClaim:
            claimName: xwiki-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xwiki-data
  namespace: xwiki
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
