name: Deploy XWiki to Recette

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - deploy
  workflow_dispatch:  # Permet de déclencher manuellement

jobs:
  deploy-recette:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Débogage des données du pull request
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "PR merged: ${{ github.event.pull_request.merged }}"
          echo "PR state: ${{ github.event.pull_request.state }}"
      - name: 🧰 Checkout repository
        uses: actions/checkout@v4

      - name: 🔐 Configure kubectl
        env:
          KUBECONFIG_CONTENTS: ${{ secrets.KUBECONFIG_CONTENTS }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBECONFIG_CONTENTS" > ~/.kube/config

      - name: 🧩 Run deployment script
        run: |
          ./scripts/ci-cd/deploy-xwiki.sh
